import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Nav from './components/Nav';
import Providers from './_provider/providers';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  let theme=`${inter.className} bg-gradient-to-r from-slate-500 to-slate-800`
  return (
    <html lang="en">
      <body className={theme}><Providers><Nav />{children}</Providers></body>
    </html>
  )
}
